In [3]:
!pip install tensorflow

In [32]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_built_with_cuda())
print(tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None))

2.19.0
True
True


In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
sentences = [
    'My name is Suraj Keshari',
    'I am twenty years old',
    'I love machine learning',
    'I love deep learning too',
    'I want to be a good AI developer'
]

In [35]:
## vocabulary size
voc_size = 1000

In [36]:
onehot_repr = [one_hot(words, voc_size) for words in sentences]
print(onehot_repr)

[[692, 555, 978, 16, 802], [638, 172, 684, 810, 377], [638, 925, 72, 781], [638, 925, 849, 781, 39], [638, 549, 262, 663, 400, 877, 350, 466]]


In [37]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
#Pre padding
sent_max_length = 10
embeded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_max_length)
print(embeded_docs)

[[  0   0   0   0   0 692 555 978  16 802]
 [  0   0   0   0   0 638 172 684 810 377]
 [  0   0   0   0   0   0 638 925  72 781]
 [  0   0   0   0   0 638 925 849 781  39]
 [  0   0 638 549 262 663 400 877 350 466]]


In [39]:
features = 10

In [40]:
model = Sequential()
model.add(Embedding(voc_size, features))
model.compile('adam', 'mse')

In [42]:

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
embeded_docs[0]

array([  0,   0,   0,   0,   0, 692, 555, 978,  16, 802], dtype=int32)

In [43]:
model.predict(embeded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[-0.00913436,  0.01124518,  0.03894002, -0.02942589, -0.01326451,
         0.0094028 ,  0.01383009, -0.03071853, -0.04270589,  0.00468266],
       [-0.00913436,  0.01124518,  0.03894002, -0.02942589, -0.01326451,
         0.0094028 ,  0.01383009, -0.03071853, -0.04270589,  0.00468266],
       [-0.00913436,  0.01124518,  0.03894002, -0.02942589, -0.01326451,
         0.0094028 ,  0.01383009, -0.03071853, -0.04270589,  0.00468266],
       [-0.00913436,  0.01124518,  0.03894002, -0.02942589, -0.01326451,
         0.0094028 ,  0.01383009, -0.03071853, -0.04270589,  0.00468266],
       [-0.00913436,  0.01124518,  0.03894002, -0.02942589, -0.01326451,
         0.0094028 ,  0.01383009, -0.03071853, -0.04270589,  0.00468266],
       [-0.0258723 , -0.04468782, -0.00349832, -0.02533717,  0.00032596,
        -0.04218421,  0.02810217,  0.03334311,  0.00136839, -0.04558865],
       [ 0.01448884,  0.04421571, -0.02101381,  0.03559282,  0.00350511,
        -0.00361084, -0.01020179, -0.04294388